export const SIGNIN = "SIGNIN";
export const SIGNOUT = "SIGNOUT";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const CLEAR_ALL_PRODUCTS = "CLEAR_ALL_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const ADD_PRODUCT_PROPERTIES = "ADD_PRODUCT_PROPERTIES";
export const TOGGLE_SELECTED_PRODUCT = "TOGGLE_SELECTED_PRODUCT";
export const TOGGLE_DESELECT_ALL_PRODUCTS = "TOGGLE_DESELECT_ALL_PRODUCTS";
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";

export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";

export const SHOW_PRODUCT_MODAL = "SHOW_PRODUCT_MODAL";
export const HIDE_PRODUCT_MODAL = "HIDE_PRODUCT_MODAL";

export const SHOW_AUTH_MODAL = "SHOW_AUTH_MODAL";
export const HIDE_AUTH_MODAL = "HIDE_AUTH_MODAL";

// export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";