export const SIGNIN = "SIGNIN";
export const SIGNOUT = "SIGNOUT";

export const ADD_DESK_PRODUCT = "ADD_DESK_PRODUCT";
export const CLEAR_ALL_DESK_PRODUCTS = "CLEAR_ALL_DESK_PRODUCTS";
export const DELETE_DESK_PRODUCT = "DELETE_DESK_PRODUCT";
export const ADD_DESK_PRODUCT_PROPERTIES = "ADD_DESK_PRODUCT_PROPERTIES";
export const TOGGLE_SELECTED_DESK_PRODUCT = "TOGGLE_SELECTED_DESK_PRODUCT";
export const TOGGLE_DESELECT_ALL_DESK_PRODUCTS = "TOGGLE_DESELECT_ALL_DESK_PRODUCTS";
export const SET_ALL_DESK_PRODUCTS = "SET_ALL_DESK_PRODUCTS";

export const SET_CURRENT_DESK_PRODUCT = "SET_CURRENT_DESK_PRODUCT";

export const SHOW_DESK_PRODUCT_MODAL = "SHOW_DESK_PRODUCT_MODAL";
export const HIDE_DESK_PRODUCT_MODAL = "HIDE_DESK_PRODUCT_MODAL";

export const SHOW_AUTH_MODAL = "SHOW_AUTH_MODAL";
export const HIDE_AUTH_MODAL = "HIDE_AUTH_MODAL";

// export const SET_CURRENT_DESK_PRODUCT = "SET_CURRENT_DESK_PRODUCT";